name: iDigCommands
version: 0.1
main: in.idig.iDigCommands.iDigCommands
commands:
   idig:
      description: idig main command
      usage: /<command> [player]
      permission: iDigCommands.basic
      permisison-message: You do not have permissions
   smack:
      description: Smack Player
      usage: /<command> [player]
      permission: iDigCommands.smack
      permisison-message: You do not have permissions
   ruler:
      description: Measure Stuff
      usage: /<command> [player]
      permission: iDigCommands.ruler
      permisison-message: You do not have permissions
   evilchase:
      description: ChasePlayers
      usage: /<command> [player]
      permission: iDigCommands.evilchase
      permisison-message: You do not have permissions
   stats:
      description: Server Usage Stats
      permission: iDigCommands.stats
      permisison-message: You do not have permissions
   faq:
      description: idig FAQ
      permission: iDigCommands.stats
      permisison-message: You do not have permissions
