name: iDigCommands
version: 0.1
main: in.idig.iDigCommands.iDigCommands
commands:
   idig:
      description: idig main command
      usage: /<command> [player]
      permission: iDigCommands.basic
      permisison-message: You do not have permissions
   smack:
      description: Smack Player
      usage: /<command> [player]
      permission: iDigCommands.smack
      permisison-message: You do not have permissions
   ruler:
      description: Measure Stuff
      usage: /<command> [player]
      permission: iDigCommands.ruler
      permisison-message: You do not have permissions
